# Generated by Django 4.2 on 2023-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('descrption', models.CharField(max_length=1000, null=True)),
                ('items_img', models.ImageField(upload_to='uploads/food_items')),
            ],
        ),
    ]
