# Generated by Django 4.2 on 2023-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='items_img',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
