# Generated by Django 4.2 on 2023-05-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0005_alter_product_items_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dabbawala.category'),
        ),
    ]
