# Generated by Django 4.2 on 2023-05-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0009_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
    ]
