# Generated by Django 4.2 on 2023-05-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0012_product_item_sub_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_sub_cat',
        ),
    ]
