# Generated by Django 4.2 on 2023-05-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0013_remove_product_item_sub_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('selected_day', models.CharField(max_length=50)),
                ('breakfast_items', models.CharField(max_length=100)),
                ('lunch_items', models.CharField(max_length=100)),
                ('dinner_items', models.CharField(max_length=100)),
            ],
        ),
    ]
