# Generated by Django 4.2 on 2023-05-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0014_cartitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
