# Generated by Django 4.2 on 2023-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0015_rename_cartitems_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
