# Generated by Django 4.2 on 2023-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0016_cartitem_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
