# Generated by Django 4.2 on 2023-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0017_cartitem_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
