# Generated by Django 4.2 on 2023-05-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0019_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
