# Generated by Django 4.1.7 on 2023-11-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0020_delete_testtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='parent_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dabbawala.category'),
        ),
    ]
