# Generated by Django 4.1.7 on 2023-11-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0023_remove_product_item_sub_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_cat',
        ),
    ]
