# Generated by Django 4.1.7 on 2023-11-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0024_remove_product_item_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_cat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_sub_cat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
