# Generated by Django 4.1.7 on 2023-11-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0025_product_item_cat_product_item_sub_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dabbawala.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_sub_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dabbawala.subcategory'),
        ),
    ]
