# Generated by Django 4.1.7 on 2023-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabbawala', '0026_alter_product_item_cat_alter_product_item_sub_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_sub_cat',
        ),
        migrations.AddField(
            model_name='product',
            name='item_sub_cat',
            field=models.ManyToManyField(to='dabbawala.subcategory'),
        ),
    ]
